service: gallery-service
frameworkVersion: '3'

plugins:
  - serverless-bundle
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-west-2

functions:
  preSignUpUserPool:
    memorySize: 128
    handler: src/handlers/preSignUpUserPool.handler
    events:
      - cognitoUserPool:
          pool: Gallery
          trigger: PreSignUp
          existing: true

  imageCompress:
    memorySize: 256
    handler: src/handlers/imageCompress.handler
    events:
      - s3:
          bucket: france31337-gallery-origin
          event: s3:ObjectCreated:*
          existing: true
    iamRoleStatements:
      - ${file(iam/imageCompressBucketOriginIAM.yml):imageCompressBucketOriginIAM}
      - ${file(iam/imageCompressBucket25IAM.yml):imageCompressBucket25IAM}
      - ${file(iam/imageCompressBucket50IAM.yml):imageCompressBucket50IAM}
